# Generated by Django 5.1.15 on 2026-04-02 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('CompanyId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=255)),
                ('Code', models.CharField(max_length=50, unique=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(blank=True, null=True)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to='users.customer', to_field='CustomerId')),
            ],
            options={
                'db_table': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('JoinedOn', models.DateTimeField(auto_now_add=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.company', to_field='CompanyId')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to='users.customer', to_field='CustomerId')),
            ],
            options={
                'db_table': 'CompanyMembers',
                'unique_together': {('Company', 'Customer')},
            },
        ),
    ]
