# Generated by Django 5.1.15 on 2026-04-02 23:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('CourseId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=500)),
                ('Description', models.TextField(blank=True, default='')),
                ('Objectives', models.JSONField(blank=True, default=list)),
                ('Category', models.CharField(blank=True, default='', max_length=255)),
                ('SubCategory', models.CharField(blank=True, default='', max_length=255)),
                ('Duration', models.CharField(blank=True, default='', max_length=100)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Currency', models.CharField(blank=True, default='SAR', max_length=10)),
                ('Link', models.URLField(blank=True, default='', max_length=1000)),
                ('Provider', models.CharField(blank=True, default='KGC', max_length=100)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('LmsEnrollmentId', models.BigIntegerField(blank=True, null=True)),
                ('MerchantOrderReference', models.CharField(max_length=255)),
                ('SponsorshipType', models.CharField(max_length=255)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CourseEnrollments',
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('CustomerId', models.UUIDField(blank=True, null=True)),
                ('CourseId', models.CharField(blank=True, max_length=255, null=True)),
                ('Rating', models.IntegerField(blank=True, null=True)),
                ('Review', models.TextField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CourseRatings',
            },
        ),
        migrations.CreateModel(
            name='KGCCandidate',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('CustomerId', models.UUIDField(blank=True, null=True)),
                ('CandidateName', models.CharField(blank=True, max_length=500, null=True)),
                ('Email', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(blank=True, max_length=100, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'KGCCandidates',
            },
        ),
    ]
