# Generated by Django 5.1.15 on 2026-04-02 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('AssessmentId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Title', models.CharField(blank=True, default='', max_length=255)),
                ('Objective', models.CharField(blank=True, default='', max_length=500)),
                ('Role', models.CharField(blank=True, default='', max_length=255)),
                ('Questions', models.JSONField(blank=True, default=list)),
                ('Responses', models.JSONField(blank=True, default=list)),
                ('OverallProgress', models.FloatField(blank=True, null=True)),
                ('TopStrength', models.CharField(blank=True, default='', max_length=255)),
                ('GrowthArea', models.CharField(blank=True, default='', max_length=255)),
                ('Skills', models.JSONField(blank=True, default=list)),
                ('TechnicalSkills', models.JSONField(blank=True, default=list)),
                ('Status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(blank=True, null=True)),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='users.customer', to_field='CustomerId')),
            ],
            options={
                'db_table': 'Assessments',
            },
        ),
    ]
