# Generated by Django 5.1.15 on 2026-04-02 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('CustomerId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Email', models.CharField(max_length=255)),
                ('CanvasUserId', models.CharField(blank=True, default='', max_length=255)),
                ('PasswordHash', models.CharField(blank=True, max_length=500, null=True)),
                ('Provider', models.CharField(blank=True, max_length=255, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('Role', models.CharField(choices=[('user', 'User'), ('company', 'Company')], default='user', max_length=20)),
                ('HasCompletedAssessment', models.BooleanField(default=False)),
                ('AssessmentCount', models.IntegerField(default=0)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerEmailVerification',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('CustomerId', models.UUIDField()),
                ('IsEmailVerified', models.BooleanField(default=False)),
                ('EmailVerificationToken', models.CharField(blank=True, max_length=500, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CustomerEmailVerifications',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('CustomerId', models.UUIDField()),
                ('FirstName', models.CharField(blank=True, max_length=255, null=True)),
                ('LastName', models.CharField(blank=True, max_length=255, null=True)),
                ('Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CustomerProfiles',
            },
        ),
        migrations.CreateModel(
            name='CustomerRefreshToken',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('CustomerId', models.UUIDField()),
                ('RefreshToken', models.CharField(blank=True, max_length=1000, null=True)),
                ('ExpiresOn', models.DateTimeField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CustomerRefreshTokens',
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('CustomerId', models.UUIDField()),
                ('PasswordResetToken', models.CharField(blank=True, max_length=500, null=True)),
                ('PasswordResetTokenExpiry', models.DateTimeField(blank=True, null=True)),
                ('IsUsed', models.BooleanField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PasswordResets',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('AgeRange', models.CharField(blank=True, default='', max_length=20)),
                ('IsWorking', models.BooleanField(default=False)),
                ('CompanyName', models.CharField(blank=True, default='', max_length=255)),
                ('CompanyIndustry', models.CharField(blank=True, default='', max_length=255)),
                ('CurrentRole', models.CharField(blank=True, default='', max_length=255)),
                ('TargetRole', models.CharField(blank=True, default='', max_length=255)),
                ('ProfessionalInterests', models.JSONField(blank=True, default=list)),
                ('CareerObjective', models.TextField(blank=True, default='')),
                ('ExperienceLevel', models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive')], default='', max_length=20)),
                ('BiggestChallenges', models.JSONField(blank=True, default=list)),
                ('Recommendations', models.JSONField(blank=True, default=list)),
                ('StudyTimePerWeek', models.CharField(blank=True, default='', max_length=50)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(blank=True, null=True)),
                ('Customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to='users.customer', to_field='CustomerId')),
            ],
            options={
                'db_table': 'ProfessionalProfiles',
            },
        ),
    ]
