# Generated by Django 5.1.15 on 2026-04-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
