# Generated by Django 5.1.15 on 2026-04-02 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualDevelopmentPlan',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('IDPId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('TargetRole', models.CharField(blank=True, default='', max_length=255)),
                ('CurrentLevel', models.CharField(blank=True, default='', max_length=255)),
                ('Timeline', models.CharField(blank=True, default='', max_length=100)),
                ('TopStrength', models.CharField(blank=True, default='', max_length=255)),
                ('GrowthArea', models.CharField(blank=True, default='', max_length=255)),
                ('SkillProficiency', models.JSONField(blank=True, default=list)),
                ('LearningRoadmap', models.JSONField(blank=True, default=list)),
                ('GeneratedBy', models.CharField(blank=True, default='', max_length=100)),
                ('GenerationCount', models.IntegerField(default=1)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(blank=True, null=True)),
                ('Assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idp', to='assessments.assessment', to_field='AssessmentId')),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idps', to='users.customer', to_field='CustomerId')),
            ],
            options={
                'db_table': 'IndividualDevelopmentPlans',
            },
        ),
    ]
